---
- name: Image Codex
  hosts: image-codex
  remote_user: root

  tasks:
    - name: Upgrade packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: "yes"
    - name: Install packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: Install Docker
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Generate SSH key
      openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519
    - name: Git checkout
      git:
        repo: git@github.com:EPFL-ENAC/image-codex.git
        dest: /opt/image-codex
        accept_hostkey: yes
