[tool.poetry]
name = "image-codex"
version = "0.1.0"
description = ""
license = "GPL-3.0-or-later"
authors = ["David Tang <david.tang@epfl.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.1"
uvicorn = "^0.15.0"
cloudinary = "^1.26.0"
Pillow = "^8.3.2"
fastapi-pagination = "^0.9.0"
requests = "^2.26.0"
exif = "^1.3.2"
ImageHash = "^4.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
python-dotenv = "^0.19.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
