name: ci

on:
  push:
    branches:
      - dev
      - main
      - feature/build
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          # FIXME cache currently not working, waiting on a new version
          # cache: "poetry"
          # cache-dependency-path: backend/poetry.lock
      - run: poetry env use "3.10"
      - run: poetry install
      - run: poetry build
      - run: poetry run pytest
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir secrets
          touch secrets/backend.env
      - run: docker-compose build
